# Discovered by skillpository-manager scan
name: "product-manager-toolkit"
type: skill
source_repo: "davila7/claude-code-templates"
source_path: "cli-tool/components/skills/business-marketing/product-manager-toolkit/SKILL.md"
source_url: "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/business-marketing/product-manager-toolkit"
description: "Comprehensive toolkit for product managers including RICE prioritization, customer interview analysis, PRD templates, discovery frameworks, and go-to-market strategies. Use for feature prioritization, user research synthesis, requirement documentation, and product strategy development."
discovered: "2026-02-07 22:29"
label: "davila7 Templates"
status: pending
