# Discovered by skillpository-manager scan
name: "product-strategist"
type: skill
source_repo: "davila7/claude-code-templates"
source_path: "cli-tool/components/skills/business-marketing/product-strategist/SKILL.md"
source_url: "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/business-marketing/product-strategist"
description: "Strategic product leadership toolkit for Head of Product including OKR cascade generation, market analysis, vision setting, and team scaling. Use for strategic planning, goal alignment, competitive analysis, and organizational design."
discovered: "2026-02-07 22:29"
label: "davila7 Templates"
status: pending
