# Discovered by skillpository-manager scan
name: "production-code-audit"
type: skill
source_repo: "davila7/claude-code-templates"
source_path: "cli-tool/components/skills/development/production-code-audit/SKILL.md"
source_url: "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/development/production-code-audit"
description: "Autonomously deep-scan entire codebase line-by-line, understand architecture and patterns, then systematically transform it to production-grade, corporate-level professional quality with optimizations"
discovered: "2026-02-07 22:29"
label: "davila7 Templates"
status: pending

rejected: "2026-02-21 18:05"
rejection_reason: "Automated batch reject - failed vetting"
