# Discovered by skillpository-manager scan
name: "database"
type: skill
source_repo: "davila7/claude-code-templates"
source_path: "cli-tool/components/skills/railway/database/SKILL.md"
source_url: "https://github.com/davila7/claude-code-templates/tree/main/cli-tool/components/skills/railway/database"
description: "Add official Railway database services (Postgres, Redis, MySQL, MongoDB). Use when user wants to add a database, says \"add postgres\", \"add redis\", \"add database\", \"connect to database\", or \"wire up the database\". For other templates (Ghost, Strapi, n8n), use the railway-templates skill."
discovered: "2026-02-07 22:29"
label: "davila7 Templates"
status: pending

rejected: "2026-02-21 18:05"
rejection_reason: "Automated batch reject - failed vetting"
